/*
 * Copyright (C) 2026
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
 *    in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. Use of this source code or binary releases for commercial purposes is strictly forbidden. This includes, without limitation,
 *    incorporation in a commercial product or incorporation into a product or project which allows commercial use.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
#include "user_interface/uiGlobals.h"
#include "user_interface/menuSystem.h"
#include "user_interface/uiUtilities.h"

// A small Nokia "Space Impact" style shooter: ship confined to the left of the screen, moves
// freely with 2/4/6/8, auto-fires to the right, aliens drift in from the right edge.
//
// The ship and alien are hand-authored monochrome sprites (displayDrawBitmap, MSB-first: the
// leftmost pixel of a row byte is bit 0x80), each drawn as two layered bitmaps -- a base shape
// plus a small accent (cockpit / eyes) in a second colour on top -- using the
// displayGetForegroundAndBackgroundColours() / displaySetForegroundAndBackgroundColours()
// save-and-restore pattern from menuIcons.c. menuIcons.h deliberately avoids hand-authored
// bitmaps because there's no simulator here to check pixel-exact byte data against; these sprites
// were instead designed as ASCII art and converted with a script
// (scratchpad/sprite_gen.py, not checked in) that renders the generated bytes straight back to
// ASCII and diffs them against the original grid before emitting the C array below -- so the byte
// data is verified pixel-exact against the intended shape without needing hardware or a
// simulator. If a sprite ever needs to change, regenerate it the same way rather than hand-editing
// the hex bytes directly. Everything else (bullets, engine flicker, explosions, starfield) stays
// vector-drawn, same as before.
//
// A stray alien that reaches the left edge without being shot or hitting the ship still costs a
// life (see the "escaped" check in advanceGame()) -- otherwise standing still and only shooting
// what's convenient would be a viable, risk-free strategy.

#define SPACE_TICK_MS                   100
#define SPACE_MARGIN                    4
#define SPACE_HUD_HEIGHT                9
#define SPACE_PLAY_TOP                  (MENU_HEADER_HEIGHT + SPACE_MARGIN + SPACE_HUD_HEIGHT)
#define SPACE_PLAY_BOTTOM               (DISPLAY_SIZE_Y - SPACE_MARGIN)
#define SPACE_PLAY_LEFT                 SPACE_MARGIN
#define SPACE_PLAY_RIGHT                (DISPLAY_SIZE_X - SPACE_MARGIN)
#define SPACE_SHIP_MAX_X                (SPACE_PLAY_LEFT + 70) // ship stays in the left portion of the screen
#define SPACE_SHIP_STEP                 3
#define SPACE_BULLET_SPEED              5
#define SPACE_BULLET_MAX                6
#define SPACE_ENEMY_SPEED               2
#define SPACE_ENEMY_MAX                 5
#define SPACE_ENEMY_VARIANTS            3
#define SPACE_EXPLOSION_MAX             3
#define SPACE_EXPLOSION_TICKS           2
#define SPACE_HIT_FLASH_TICKS           3
#define SPACE_STAR_COUNT                10
#define SPACE_FIRE_INTERVAL_MS          400
#define SPACE_ENEMY_SPAWN_INTERVAL_MS   800
#define SPACE_INITIAL_LIVES             3

// RGB888 colours, converted via displayConvertRGB888ToNative() before use (same pattern as
// menuIcons.c) rather than baked-in native constants, so they read the same on every panel type.
#define SPACE_COLOUR_SHIP_HULL     0x00E5FFU // cyan
#define SPACE_COLOUR_SHIP_COCKPIT  0xFFFFFFU // white
#define SPACE_COLOUR_SHIP_ENGINE   0xFFA000U // orange
#define SPACE_COLOUR_ALIEN_EYES    0xFFFFFFU // white
#define SPACE_COLOUR_BULLET        0xFFEB3BU // yellow
#define SPACE_COLOUR_BULLET_TRAIL  0x8D8A1FU // dim yellow
#define SPACE_COLOUR_STAR          0x424242U // dim grey
#define SPACE_COLOUR_EXPLOSION     0xFF6D00U // orange
#define SPACE_COLOUR_FLASH_BORDER  0xFF1744U // bright red

// Ship sprite: 16x11, top-down fighter facing right, mirror-symmetric top/bottom. The draw-offset
// constants place the bitmap's nose (col 15) at (shipX+4, shipY) -- the same point the ship's
// previous vector-triangle nose sat at -- so bullets (spawned at shipX+4) still leave from the tip.
#define SPACE_SHIP_SPRITE_W        16
#define SPACE_SHIP_SPRITE_H        11
#define SPACE_SHIP_DRAW_X_OFFSET   (-11)
#define SPACE_SHIP_DRAW_Y_OFFSET   (-5)
// Leftmost lit pixel in the sprite is 9 columns left of shipX (not the full 11-wide bitmap width,
// since columns 0-1 of every row are blank) -- used to keep the tail from drawing past the
// playfield's left edge when the ship is moved all the way back.
#define SPACE_SHIP_BACK_MARGIN     9

static const uint8_t spaceShipHullBitmap[22] = // 16x11 -- user-edited via scratchpad CSV round trip
{
	0x00U, 0x00U, // ................
	0x01U, 0x00U, // .......#........
	0x01U, 0x80U, // .......##.......
	0x11U, 0xC0U, // ...#...###......
	0x19U, 0xF8U, // ...##..######...
	0x3DU, 0xFFU, // ..####.#########
	0x19U, 0xF8U, // ...##..######...
	0x11U, 0xC0U, // ...#...###......
	0x01U, 0x80U, // .......##.......
	0x01U, 0x00U, // .......#........
	0x00U, 0x00U, // ................
};

static const uint8_t spaceShipCockpitBitmap[22] = // 16x11
{
	0x00U, 0x00U, // ................
	0x00U, 0x00U, // ................
	0x00U, 0x00U, // ................
	0x00U, 0x00U, // ................
	0x00U, 0x20U, // ..........#.....
	0x00U, 0x60U, // .........##.....
	0x00U, 0x20U, // ..........#.....
	0x00U, 0x00U, // ................
	0x00U, 0x00U, // ................
	0x00U, 0x00U, // ................
	0x00U, 0x00U, // ................
};

// Alien sprite: 11x8, the classic "crab" invader silhouette -- immediately readable as "alien"
// even at this size, which a plain circle wasn't.
#define SPACE_ALIEN_SPRITE_W       11
#define SPACE_ALIEN_SPRITE_H       8
#define SPACE_ALIEN_DRAW_X_OFFSET  (-5)
#define SPACE_ALIEN_DRAW_Y_OFFSET  (-4)

static const uint8_t spaceAlienBodyBitmap[16] = // 11x8
{
	0x20U, 0x80U, // ..#.....#..
	0x11U, 0x00U, // ...#...#...
	0x3FU, 0x80U, // ..#######..
	0x6EU, 0xC0U, // .##.###.##.
	0xFFU, 0xE0U, // ###########
	0xBFU, 0xA0U, // #.#######.#
	0xA0U, 0xA0U, // #.#.....#.#
	0x1BU, 0x00U, // ...##.##...
};

static const uint8_t spaceAlienEyesBitmap[16] = // 11x8
{
	0x00U, 0x00U, // ...........
	0x00U, 0x00U, // ...........
	0x20U, 0x80U, // ..#.....#..
	0x00U, 0x00U, // ...........
	0x00U, 0x00U, // ...........
	0x00U, 0x00U, // ...........
	0x00U, 0x00U, // ...........
	0x00U, 0x00U, // ...........
};

typedef struct
{
	int16_t x;
	int16_t y;
	bool active;
	uint8_t variant; // enemies only: picks a body colour, ignored for bullets
} spaceEntity_t;

typedef struct
{
	int16_t x;
	int16_t y;
	uint8_t ttl;
} spaceExplosion_t;

static menuStatus_t menuGameSpaceExitCode = MENU_STATUS_SUCCESS;
static int16_t shipX;
static int16_t shipY;
static bool moveUpHeld;
static bool moveDownHeld;
static bool moveLeftHeld;
static bool moveRightHeld;
static spaceEntity_t bullets[SPACE_BULLET_MAX];
static spaceEntity_t enemies[SPACE_ENEMY_MAX];
static spaceExplosion_t explosions[SPACE_EXPLOSION_MAX];
static int16_t starX[SPACE_STAR_COUNT];
static int16_t starY[SPACE_STAR_COUNT];
static bool engineFlicker;
static uint8_t hitFlashTicks;
static int lives;
static int score;
static bool gameOver;
static uint32_t lastTickTime;
static uint32_t lastFireTime;
static uint32_t lastSpawnTime;
static uint32_t rngState;

static void updateScreen(bool isFirstRun);
static void handleEvent(uiEvent_t *ev);
static void resetGame(void);
static uint32_t nextRandom(void);
static void spawnEnemy(void);
static void fireBullet(void);
static void spawnExplosion(int16_t x, int16_t y);
static void loseLife(void);
static void advanceGame(void);

menuStatus_t menuGameSpace(uiEvent_t *ev, bool isFirstRun)
{
	if (isFirstRun)
	{
		menuDataGlobal.numItems = 0;
		lastTickTime = ev->time;
		lastFireTime = ev->time;
		lastSpawnTime = ev->time;
		resetGame();
		updateScreen(true);
	}
	else
	{
		menuGameSpaceExitCode = MENU_STATUS_SUCCESS;

		if (ev->hasEvent)
		{
			handleEvent(ev);
		}

		if (gameOver == false)
		{
			if ((ev->time - lastFireTime) > SPACE_FIRE_INTERVAL_MS)
			{
				lastFireTime = ev->time;
				fireBullet();
			}

			if ((ev->time - lastSpawnTime) > SPACE_ENEMY_SPAWN_INTERVAL_MS)
			{
				lastSpawnTime = ev->time;
				spawnEnemy();
			}

			if ((ev->time - lastTickTime) > SPACE_TICK_MS)
			{
				lastTickTime = ev->time;
				advanceGame();
				updateScreen(false);
			}
		}
	}

	return menuGameSpaceExitCode;
}

static void resetGame(void)
{
	shipX = (int16_t)(SPACE_PLAY_LEFT + 10);
	shipY = (int16_t)((SPACE_PLAY_TOP + SPACE_PLAY_BOTTOM) / 2);
	moveUpHeld = false;
	moveDownHeld = false;
	moveLeftHeld = false;
	moveRightHeld = false;
	engineFlicker = false;
	hitFlashTicks = 0;

	for (int i = 0; i < SPACE_BULLET_MAX; i++)
	{
		bullets[i].active = false;
	}

	for (int i = 0; i < SPACE_ENEMY_MAX; i++)
	{
		enemies[i].active = false;
	}

	for (int i = 0; i < SPACE_EXPLOSION_MAX; i++)
	{
		explosions[i].ttl = 0;
	}

	lives = SPACE_INITIAL_LIVES;
	score = 0;
	gameOver = false;
	rngState = ticksGetMillis();

	for (int i = 0; i < SPACE_STAR_COUNT; i++)
	{
		starX[i] = (int16_t)(SPACE_PLAY_LEFT + (nextRandom() % (SPACE_PLAY_RIGHT - SPACE_PLAY_LEFT)));
		starY[i] = (int16_t)(SPACE_PLAY_TOP + (nextRandom() % (SPACE_PLAY_BOTTOM - SPACE_PLAY_TOP)));
	}
}

static uint32_t nextRandom(void)
{
	// Small self-contained LCG -- see [[feedback_no_libc_rand]]: this codebase avoids libc
	// rand()/srand() after they caused a hardware freeze in the Snake game.
	rngState = ((rngState * 1103515245u) + 12345u);
	return ((rngState >> 16) & 0x7FFFu);
}

static void spawnEnemy(void)
{
	for (int i = 0; i < SPACE_ENEMY_MAX; i++)
	{
		if (enemies[i].active == false)
		{
			enemies[i].active = true;
			enemies[i].x = SPACE_PLAY_RIGHT;
			enemies[i].y = (int16_t)(SPACE_PLAY_TOP + (nextRandom() % (SPACE_PLAY_BOTTOM - SPACE_PLAY_TOP)));
			enemies[i].variant = (uint8_t)(nextRandom() % SPACE_ENEMY_VARIANTS);
			return;
		}
	}
}

static void fireBullet(void)
{
	for (int i = 0; i < SPACE_BULLET_MAX; i++)
	{
		if (bullets[i].active == false)
		{
			bullets[i].active = true;
			bullets[i].x = (int16_t)(shipX + 4);
			bullets[i].y = shipY;
			return;
		}
	}
}

static void spawnExplosion(int16_t x, int16_t y)
{
	for (int i = 0; i < SPACE_EXPLOSION_MAX; i++)
	{
		if (explosions[i].ttl == 0)
		{
			explosions[i].x = x;
			explosions[i].y = y;
			explosions[i].ttl = SPACE_EXPLOSION_TICKS;
			return;
		}
	}
}

static void loseLife(void)
{
	hitFlashTicks = SPACE_HIT_FLASH_TICKS;
	lives--;

	if (lives <= 0)
	{
		gameOver = true;
	}
}

static void advanceGame(void)
{
	if (moveUpHeld && (shipY > (SPACE_PLAY_TOP + 4)))
	{
		shipY = (int16_t)(shipY - SPACE_SHIP_STEP);
	}

	if (moveDownHeld && (shipY < (SPACE_PLAY_BOTTOM - 4)))
	{
		shipY = (int16_t)(shipY + SPACE_SHIP_STEP);
	}

	if (moveLeftHeld && (shipX > (SPACE_PLAY_LEFT + SPACE_SHIP_BACK_MARGIN)))
	{
		shipX = (int16_t)(shipX - SPACE_SHIP_STEP);
	}

	if (moveRightHeld && (shipX < SPACE_SHIP_MAX_X))
	{
		shipX = (int16_t)(shipX + SPACE_SHIP_STEP);
	}

	engineFlicker = !engineFlicker;

	if (hitFlashTicks > 0)
	{
		hitFlashTicks--;
	}

	for (int i = 0; i < SPACE_EXPLOSION_MAX; i++)
	{
		if (explosions[i].ttl > 0)
		{
			explosions[i].ttl--;
		}
	}

	for (int i = 0; i < SPACE_BULLET_MAX; i++)
	{
		if (bullets[i].active)
		{
			bullets[i].x = (int16_t)(bullets[i].x + SPACE_BULLET_SPEED);

			if (bullets[i].x > SPACE_PLAY_RIGHT)
			{
				bullets[i].active = false;
			}
		}
	}

	// Enemies move but are NOT despawned here on reaching the left edge -- that's handled after
	// collisions below, so a bullet/ship hit on the same tick takes priority over the "escaped"
	// penalty for an enemy that happens to cross both the ship's position and the edge at once.
	for (int i = 0; i < SPACE_ENEMY_MAX; i++)
	{
		if (enemies[i].active)
		{
			enemies[i].x = (int16_t)(enemies[i].x - SPACE_ENEMY_SPEED);
		}
	}

	for (int b = 0; b < SPACE_BULLET_MAX; b++)
	{
		if (bullets[b].active == false)
		{
			continue;
		}

		for (int e = 0; e < SPACE_ENEMY_MAX; e++)
		{
			int16_t dx, dy;

			if (enemies[e].active == false)
			{
				continue;
			}

			dx = (int16_t)(bullets[b].x - enemies[e].x);
			dy = (int16_t)(bullets[b].y - enemies[e].y);

			if ((dx > -5) && (dx < 5) && (dy > -5) && (dy < 5))
			{
				spawnExplosion(enemies[e].x, enemies[e].y);
				bullets[b].active = false;
				enemies[e].active = false;
				score++;
				break;
			}
		}
	}

	for (int e = 0; e < SPACE_ENEMY_MAX; e++)
	{
		int16_t dx, dy;

		if (enemies[e].active == false)
		{
			continue;
		}

		dx = (int16_t)(enemies[e].x - shipX);
		dy = (int16_t)(enemies[e].y - shipY);

		if ((dx > -6) && (dx < 6) && (dy > -6) && (dy < 6))
		{
			spawnExplosion(enemies[e].x, enemies[e].y);
			enemies[e].active = false;
			loseLife();
		}
	}

	// Any enemy still active but past the left edge got past the ship without being shot down --
	// that costs a life too, otherwise sitting still and only shooting convenient targets would be
	// a risk-free strategy.
	for (int e = 0; e < SPACE_ENEMY_MAX; e++)
	{
		if (enemies[e].active && (enemies[e].x < SPACE_PLAY_LEFT))
		{
			enemies[e].active = false;
			loseLife();
		}
	}
}

static void updateScreen(bool isFirstRun)
{
	char buffer[24];
	uint16_t savedFg, savedBg;

	if (isFirstRun)
	{
		displayClearBuf();
		menuDisplayTitle("Space");
	}

	displayThemeApply(THEME_ITEM_FG_DECORATION, THEME_ITEM_BG);
	displayFillRect(0, MENU_HEADER_HEIGHT, DISPLAY_SIZE_X, (DISPLAY_SIZE_Y - MENU_HEADER_HEIGHT), true); // clear playfield to background

	displayGetForegroundAndBackgroundColours(&savedFg, &savedBg);

	// Starfield -- static dim dots for a bit of depth behind the action.
	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_STAR), savedBg);
	for (int i = 0; i < SPACE_STAR_COUNT; i++)
	{
		displaySetPixel(starX[i], starY[i], true);
	}

	// Ship -- hull + cockpit bitmaps (see the sprite block up top) plus a flickering vector engine
	// trail (2/3-tick alternation for a cheap animated-thruster look without extra timing state),
	// anchored at the sprite's tail. The flat base sits against the tail and the point trails away
	// to the left -- flame wide where it's attached, tapering as it trails off, not the other way.
	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_SHIP_ENGINE), savedBg);
	displayFillTriangle((int16_t)(shipX - SPACE_SHIP_BACK_MARGIN - (engineFlicker ? 4 : 2)), shipY,
	                     (int16_t)(shipX - SPACE_SHIP_BACK_MARGIN), (int16_t)(shipY - 2),
	                     (int16_t)(shipX - SPACE_SHIP_BACK_MARGIN), (int16_t)(shipY + 2), true);

	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_SHIP_HULL), savedBg);
	displayDrawBitmap((int16_t)(shipX + SPACE_SHIP_DRAW_X_OFFSET), (int16_t)(shipY + SPACE_SHIP_DRAW_Y_OFFSET),
	                   (uint8_t *)spaceShipHullBitmap, SPACE_SHIP_SPRITE_W, SPACE_SHIP_SPRITE_H, true);

	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_SHIP_COCKPIT), savedBg);
	displayDrawBitmap((int16_t)(shipX + SPACE_SHIP_DRAW_X_OFFSET), (int16_t)(shipY + SPACE_SHIP_DRAW_Y_OFFSET),
	                   (uint8_t *)spaceShipCockpitBitmap, SPACE_SHIP_SPRITE_W, SPACE_SHIP_SPRITE_H, true);

	// Bullets -- bright head (direct displayFillRect: false=foreground, the opposite convention
	// to every other primitive here, see menuIcons.c) plus a dim trailing pixel for a streak look.
	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_BULLET_TRAIL), savedBg);
	for (int i = 0; i < SPACE_BULLET_MAX; i++)
	{
		if (bullets[i].active)
		{
			displaySetPixel((int16_t)(bullets[i].x - 2), bullets[i].y, true);
		}
	}

	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_BULLET), savedBg);
	for (int i = 0; i < SPACE_BULLET_MAX; i++)
	{
		if (bullets[i].active)
		{
			displayFillRect(bullets[i].x, (int16_t)(bullets[i].y - 1), 3, 2, false); // direct fillRect: false=foreground
		}
	}

	// Aliens -- the "crab" sprite (see the sprite block up top), body colour picked per-spawn by
	// variant, with a small white eye accent layered on top.
	static const uint32_t alienBodyColours[SPACE_ENEMY_VARIANTS] = { 0xFF5252U, 0xAB47BCU, 0x66BB6AU };
	for (int i = 0; i < SPACE_ENEMY_MAX; i++)
	{
		if (enemies[i].active)
		{
			int16_t drawX = (int16_t)(enemies[i].x + SPACE_ALIEN_DRAW_X_OFFSET);
			int16_t drawY = (int16_t)(enemies[i].y + SPACE_ALIEN_DRAW_Y_OFFSET);

			displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(alienBodyColours[enemies[i].variant % SPACE_ENEMY_VARIANTS]), savedBg);
			displayDrawBitmap(drawX, drawY, (uint8_t *)spaceAlienBodyBitmap, SPACE_ALIEN_SPRITE_W, SPACE_ALIEN_SPRITE_H, true);

			displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_ALIEN_EYES), savedBg);
			displayDrawBitmap(drawX, drawY, (uint8_t *)spaceAlienEyesBitmap, SPACE_ALIEN_SPRITE_W, SPACE_ALIEN_SPRITE_H, true);
		}
	}

	// Explosions -- a brief 4-point burst that shrinks over its 2-tick lifetime.
	displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_EXPLOSION), savedBg);
	for (int i = 0; i < SPACE_EXPLOSION_MAX; i++)
	{
		if (explosions[i].ttl > 0)
		{
			int16_t r = (int16_t)(explosions[i].ttl == SPACE_EXPLOSION_TICKS ? 4 : 2);
			int16_t ex = explosions[i].x;
			int16_t ey = explosions[i].y;

			displayDrawLine((int16_t)(ex - r), (int16_t)(ey - r), (int16_t)(ex + r), (int16_t)(ey + r), true);
			displayDrawLine((int16_t)(ex - r), (int16_t)(ey + r), (int16_t)(ex + r), (int16_t)(ey - r), true);
		}
	}

	displaySetForegroundAndBackgroundColours(savedFg, savedBg);

	// Hit flash -- a bright border around the playfield for a couple of ticks whenever a life is
	// lost, so losing a life to an escaped alien (easy to miss, off-screen) is still noticeable.
	if (hitFlashTicks > 0)
	{
		displaySetForegroundAndBackgroundColours(displayConvertRGB888ToNative(SPACE_COLOUR_FLASH_BORDER), savedBg);
		displayDrawRect(0, MENU_HEADER_HEIGHT, DISPLAY_SIZE_X, (int16_t)(DISPLAY_SIZE_Y - MENU_HEADER_HEIGHT), true);
		displaySetForegroundAndBackgroundColours(savedFg, savedBg);
	}

	snprintf(buffer, sizeof(buffer), "Score:%d", score);
	displayPrintAt(SPACE_MARGIN, (MENU_HEADER_HEIGHT + 1), buffer, FONT_SIZE_1);
	snprintf(buffer, sizeof(buffer), "Lives:%d", lives);
	displayPrintAt((DISPLAY_SIZE_X - SPACE_MARGIN - 42), (MENU_HEADER_HEIGHT + 1), buffer, FONT_SIZE_1); // "Lives:N" is ~42px at FONT_SIZE_1

	if (gameOver)
	{
		snprintf(buffer, sizeof(buffer), "Score: %d", score);
		displayPrintCentered(((DISPLAY_SIZE_Y / 2) - 8), "GAME OVER", FONT_SIZE_2);
		displayPrintCentered(((DISPLAY_SIZE_Y / 2) + 6), buffer, FONT_SIZE_1);
	}

	displayThemeResetToDefault();
	displayRender();
}

static void handleEvent(uiEvent_t *ev)
{
	if (ev->events & FUNCTION_EVENT)
	{
		if (ev->function == FUNC_REDRAW)
		{
			updateScreen(false);
		}
		return;
	}

	if (KEYCHECK_SHORTUP(ev->keys, KEY_RED) || KEYCHECK_SHORTUP(ev->keys, KEY_GREEN))
	{
		menuSystemPopPreviousMenu();
		return;
	}

	if (gameOver)
	{
		return; // Only the exit keys do anything once the game has ended.
	}

	// Track held state (rather than moving on each press event) so the ship moves smoothly every
	// tick for as long as a direction key is held, instead of at the keyboard's own repeat rate.
	if (KEYCHECK_DOWN(ev->keys, KEY_2))
	{
		moveUpHeld = true;
	}
	else if (KEYCHECK_UP(ev->keys, KEY_2))
	{
		moveUpHeld = false;
	}

	if (KEYCHECK_DOWN(ev->keys, KEY_8))
	{
		moveDownHeld = true;
	}
	else if (KEYCHECK_UP(ev->keys, KEY_8))
	{
		moveDownHeld = false;
	}

	if (KEYCHECK_DOWN(ev->keys, KEY_4))
	{
		moveLeftHeld = true;
	}
	else if (KEYCHECK_UP(ev->keys, KEY_4))
	{
		moveLeftHeld = false;
	}

	if (KEYCHECK_DOWN(ev->keys, KEY_6))
	{
		moveRightHeld = true;
	}
	else if (KEYCHECK_UP(ev->keys, KEY_6))
	{
		moveRightHeld = false;
	}
}
